name: pysros
dependencies:
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - libedit=3.1.20191231
  - libffi=3.3
  - ncurses=6.2
  - openssl=1.1.1j
  - pip=20.0.2
  - python=3.8.8
  - readline=8.1
  - setuptools=52.0.0
  - sqlite=3.33.0
  - tk=8.6.10
  - wheel=0.36.2
  - xz=5.2.5
  - zlib=1.2.11
  - pip:
    - aiocontextvars==0.2.2
    - charset-normalizer==2.0.4
    - ciscoconfparse==1.5.46
    - contextvars==2.4
    - dictdiffer==0.9.0
    - dnspython==2.1.0
    - idna==3.2
    - immutables==0.16
    - iniconfig==1.1.1
    - jinja2==3.0.1
    - junos-eznc==2.6.2
    - loguru==0.5.3
    - markupsafe==2.0.1
    - napalm==3.3.1
    - netmiko==3.4.0
    - ntc-templates==2.2.2
    - passlib==1.7.4
    - py==1.10.0
    - pyeapi==0.8.4
    - pyserial==3.5
    - pytest==6.2.4
    - requests==2.26.0
    - scp==0.13.6
    - textfsm==1.1.2
    - toml==0.10.2
    - transitions==0.8.8
    - typing-extensions==3.10.0.0
    - urllib3==1.26.6
    - xmltodict==0.12.0
    - yamlordereddictloader==0.4.0
    - napalm-sros==0.1.0.21ff35
    - https://dist-u.linx.net/linx-python/pysros/pysros-0.0.3.tar.gz
